os: osx
env: 
  - OSX=10.14
osx_image: xcode10.1

rvm: system
language: ruby

before_install:
  - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair

script:
  - brew audit --verbose --new-formula Formula/metanorma.rb || true # sometimes it fails because of GitHub API Error: API rate limit exceeded for
  - brew install --verbose --debug metanorma
  - brew test --verbose --debug metanorma
  - brew uninstall --debug metanorma
  # test upgrade
  - git checkout v1.1.3
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install --verbose --debug metanorma
  - git checkout $TRAVIS_COMMIT
  - brew upgrade --verbose --debug metanorma

addons:
  ssh_known_hosts: github.com
