language: ruby
rvm: system
os: osx
env: OSX=10.12
osx_image: xcode8.3
sudo: required

before_install:
  - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair

script:
  - brew install -v metanorma

addons:
  ssh_known_hosts: github.com
