os: osx
env: 
  - OSX=10.14
osx_image: xcode10.1

rvm: system
language: ruby

before_install:
  - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair

script:
  - brew audit --new-formula Formula/metanorma.rb || true # sometimes it fails because of GitHub API Error: API rate limit exceeded for
  - brew install metanorma
  - brew test metanorma
  - brew uninstall metanorma

addons:
  ssh_known_hosts: github.com
