os: osx
env: 
  - OSX=10.14
osx_image: xcode10.1

rvm: system
language: ruby

before_install:
  - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair

script:
  - brew audit --verbose --new-formula Formula/metanorma.rb || true # sometimes it fails because of GitHub API Error: API rate limit exceeded for
  - brew install --verbose --debug metanorma
  # remove line below once https://github.com/metanorma/metanorma-standoc/pull/63 released
  - sed -i.bak "s/'r+'/'r+', :external_encoding=>'UTF-8'/" /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-standoc-1.1.6/lib/asciidoctor/standoc/inline.rb
  - brew test --verbose --debug metanorma

addons:
  ssh_known_hosts: github.com
