language: ruby
matrix:
  include:
    - env: OSX=10.14
      os: osx
      osx_image: xcode10.2
      rvm: system
    - env: OSX=10.13
      os: osx
      osx_image: xcode10.1
      rvm: system
    - env: OSX=10.12
      os: osx
      osx_image: xcode9.2
      rvm: 2.3

before_install:
  - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair

script:
  - brew audit --new-formula Formula/metanorma.rb || true # sometimes it fails because of GitHub API Error: API rate limit exceeded for
  - brew install metanorma
  - brew test metanorma
  - brew uninstall metanorma

addons:
  ssh_known_hosts: github.com
