name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - 'Formula/*.rb'
      # - '!.github/workflows/*'

jobs:
  build-linux:
    name: Install on Linux
    runs-on: ubuntu-latest
    container: homebrew/brew
    steps:
      - name: Update Homebrew
        run: |
          brew update-reset
      - name: Checkout tap
        uses: actions/checkout@master
      - name: Setup tap
        run: |
          mkdir -p $(dirname $(brew --repository $GITHUB_REPOSITORY))
          ln -s $PWD $(brew --repository $GITHUB_REPOSITORY)

      - name: Brew audit
        # Sometimes it fails because of GitHub API Error: API rate limit exceeded for
        run: |
          brew audit --new-formula Formula/metanorma.rb

      - name: Brew install
        run: |
          brew install --build-from-source Formula/metanorma.rb

      - name: Test
        run: |
          brew test metanorma
          metanorma help

      - name: Uninstall
        run: |
          brew uninstall metanorma

      # - name: Build bottles
      #   env:
      #     HOMEBREW_BINTRAY_URL: https://dl.bintray.com/${{github.event.repository.owner.login}}/bottles-tap
      #   run: |
      #     mkdir ~/bottles
      #     cd ~/bottles
      #     brew test-bot --root-url=$HOMEBREW_BINTRAY_URL
      #     mv ~/bottles $GITHUB_WORKSPACE
      # - name: Cache bottles
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: bottles
      #     path: bottles
