name: linux

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-linux:
    name: Install on Linux
    runs-on: ubuntu-latest
    container: homebrew/brew
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        formula: [ 'metanorma' ]
        experimental: [ false ]
        include:
          - formula: 'metanorma-dev'
            experimental: true
    steps:
      - uses: actions/checkout@v2

      # https://github.com/actions/checkout/issues/6
      - if: ${{ github.event_name == 'pull_request' }}
        run: git switch -c "pull-request"

      - uses: actions/cache@v2
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      - run: brew update-reset

      - name: Setup tap
        run: |
          mkdir -p $(dirname $(brew --repository $GITHUB_REPOSITORY))
          ln -s $PWD $(brew --repository $GITHUB_REPOSITORY)
          brew tap linuxbrew/xorg

      - run: | # https://apple.stackexchange.com/a/402401/65949
          find "$(brew --prefix)/Caskroom/"*'/.metadata' -type f -name '*.rb' |
            xargs grep 'EOS.undent' --files-with-matches |
            xargs sed -i '' 's/EOS.undent/EOS/'

      - name: Workaraund perl installation
        # https://github.com/agracio/electron-edge-js/issues/16#issuecomment-385620483
        run: ln -s /usr/include/locale.h /usr/include/xlocale.h

      - run: brew audit --strict --formula Formula/${{ matrix.formula }}.rb
        continue-on-error: true

      - run: brew install --build-from-source --verbose --include-test Formula/${{ matrix.formula }}.rb

      - run: metanorma help

      - run: brew test ${{ matrix.formula }}

      - run: brew uninstall ${{ matrix.formula }}
