name: linux

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-linux:
    name: Install on Linux
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew:latest
      options: --user root
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        formula: [ 'metanorma' ]
        experimental: [ false ]
        include:
          - formula: 'metanorma-dev'
            experimental: true
    steps:
      # https://github.com/actions/checkout/issues/124#issuecomment-606277160
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v2
        if: github.event_name == 'push'

      - uses: actions/cache@v2
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      - run: brew update-reset

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y libpng16-16 libfreetype6 libfontconfig

      - run: brew audit --strict --formula Formula/${{ matrix.formula }}.rb
        continue-on-error: true

      - run: brew install --build-from-source --verbose --include-test --formula Formula/${{ matrix.formula }}.rb

      - run: metanorma help

      - run: brew test ${{ matrix.formula }}

      - run: brew uninstall ${{ matrix.formula }}
