name: linux

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-linux:
    name: Install on Linux
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.formula }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        formula: [ metanorma, xml2rfc ]
        experimental: [ false ]
        include:
          - formula: metanorma-dev
            executable: metanorma
            experimental: true
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      # https://docs.brew.sh/Homebrew-on-Linux
      - run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
          test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          test -r ~/.bash_profile && echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bash_profile
          echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.profile
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - run: brew update-reset

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y libpng16-16 libfreetype6 libfontconfig

      - run: brew install --build-from-source --verbose --include-test --formula Formula/${{ matrix.formula }}.rb
        # To ignore potential: The `brew link` step did not complete successfully
        continue-on-error: true

      - run: which ${{ matrix.executable || matrix.formula }}

      - run: brew test ${{ matrix.formula }}

      - run: brew uninstall ${{ matrix.formula }}
