name: macos

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-macos:
    name: Install macOS
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-12 ]
        formula: [ metanorma ]
        experimental: [ false ]
        include:
          - formula: metanorma-dev
            os: macos-12
            experimental: true
            executable: metanorma
          - formula: metanorma-dev
            os: macos-14
            experimental: true
            executable: metanorma

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.os }}-${{ matrix.formula }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      - run: brew update-reset

      - name: setup tap
        run: |
          mkdir -p $(dirname $(brew --repository $GITHUB_REPOSITORY))
          ln -s $PWD $(brew --repository $GITHUB_REPOSITORY)

      - run: |
          brew install --build-from-source --verbose --formula Formula/${{ matrix.formula }}.rb
        # To ignore potential: The `brew link` step did not complete successfully
        continue-on-error: true

      - run: brew audit --strict --formula ${{ matrix.formula }}
        # To ignore potential: GitHub API Error: API rate limit exceeded for
        continue-on-error: true

      - run: which ${{ matrix.executable || matrix.formula }}

      - run: brew test --verbose ${{ matrix.formula }}
        continue-on-error: true # Because ietf test fails anyway

      - run: brew uninstall ${{ matrix.formula }}
