name: macos

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-macos:
    name: Install macOS
    runs-on: macos-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        formula: [ 'metanorma' ]
        experimental: [ false ]
        include:
          - formula: 'metanorma-dev'
            experimental: true
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      - run: brew update-reset

      - name: setup tap
        run: |
          mkdir -p $(dirname $(brew --repository $GITHUB_REPOSITORY))
          ln -s $PWD $(brew --repository $GITHUB_REPOSITORY)

      - run: brew audit --strict --formula Formula/${{ matrix.formula }}.rb
        # Sometimes it fails because of GitHub API Error: API rate limit exceeded for
        continue-on-error: true

      - run: brew install --build-from-source --verbose Formula/${{ matrix.formula }}.rb

      - run: |
          brew test ${{ matrix.formula }}
          metanorma help

      - run: brew uninstall ${{ matrix.formula }}
