name: macos

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Create Gemfile
        run: |
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'metanorma-cli', '1.12.8'" >> Gemfile

      - name: Install bundler
        run: gem install bundler

      - name: Add multiple platforms to lockfile
        run: |
          bundle lock --add-platform x86_64-linux
          bundle lock --add-platform x64-mingw32
          bundle lock --add-platform arm64-darwin
          bundle lock --add-platform x86_64-darwin

      - name: Install dependencies
        run: bundle install

      - name: Upload lockfile artifact
        uses: actions/upload-artifact@v4
        with:
          name: gemfile-lock
          path: Gemfile.lock

  test-macos:
    name: Install macOS
    strategy:
      fail-fast: false
      matrix:
        # macos-13: intel; macos-14, macos-15: arm64
        os: [ macos-15, macos-14, macos-13 ]
        formula: [ metanorma ]
        experimental: [ false ]

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.os }}-${{ matrix.formula }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      - run: brew update-reset

      - name: setup tap
        run: |
          mkdir -p $(dirname $(brew --repository $GITHUB_REPOSITORY))
          ln -s $PWD $(brew --repository $GITHUB_REPOSITORY)

      - run: |
          brew install --build-from-source --verbose --formula Formula/${{ matrix.formula }}.rb
        # To ignore potential: The `brew link` step did not complete successfully
        #continue-on-error: true

      - run: brew audit --strict --formula ${{ matrix.formula }}
        # To ignore potential: GitHub API Error: API rate limit exceeded for
        #  Files were found with references to the Homebrew shims directory.
        #    The offending files are:
        #      libexec/gems/sqlite3-1.7.3/ext/sqlite3/tmp/arm64-apple-darwin24.4.0/ports/sqlite3/3.45.2/sqlite-autoconf-3450200/config.log
        continue-on-error: ${{ matrix.experimental }}

      - run: which ${{ matrix.executable || matrix.formula }}

      - run: |
          brew linkage ${{ matrix.formula }}
          brew linkage --reverse ${{ matrix.formula }}
          brew linkage --test ${{ matrix.formula }}

      - run: which ${{ matrix.executable || matrix.formula }}

      - run: brew test --verbose ${{ matrix.formula }}
        #continue-on-error: true # Because ietf test fails anyway

      - run: brew uninstall ${{ matrix.formula }}
