name: macos

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-macos:
    name: Install macOS
    strategy:
      fail-fast: false
      matrix:
        # macos-13: intel; macos-14, macos-15: arm64
        os: [ macos-15, macos-14, macos-13 ]
        formula: [ metanorma ]
        experimental: [ false ]
        # include:
        #   - formula: metanorma-dev
        #     os: macos-15
        #     experimental: true
        #     executable: metanorma
        #   - formula: metanorma-dev
        #     os: macos-13
        #     experimental: true
        #     executable: metanorma

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.os }}-${{ matrix.formula }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      - run: brew update-reset

      - name: Add local tap for testing
        run: brew tap metanorma/metanorma $GITHUB_WORKSPACE

      - name: Install inkscape (required for tests)
        run: brew install --cask inkscape

      - run: |
          brew install --build-from-source --verbose metanorma/metanorma/${{ matrix.formula }}
        # To ignore potential: The `brew link` step did not complete successfully
        #continue-on-error: true

      - run: brew audit --strict --formula metanorma/metanorma/${{ matrix.formula }}
        # To ignore potential: GitHub API Error: API rate limit exceeded for
        #  Files were found with references to the Homebrew shims directory.
        #    The offending files are:
        #      libexec/gems/sqlite3-1.7.3/ext/sqlite3/tmp/arm64-apple-darwin24.4.0/ports/sqlite3/3.45.2/sqlite-autoconf-3450200/config.log
        continue-on-error: ${{ matrix.experimental }}

      - run: which ${{ matrix.executable || matrix.formula }}

      - run: brew test --verbose metanorma/metanorma/${{ matrix.formula }}
        #continue-on-error: true # Because ietf test fails anyway

      - run: brew uninstall metanorma/metanorma/${{ matrix.formula }}
