name: release-tag

on:
  repository_dispatch:
    types: [ metanorma/packed-mn ]
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version.
        required: true

jobs:
  push-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.event.client_payload.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - name: Parse metanorma-cli version
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: echo METANORMA_CLI_VERSION=${{ github.event.inputs.next_version }} >> ${GITHUB_ENV}

    - name: Parse metanorma-cli version
      if: ${{ github.event_name == 'repository_dispatch' }}
      run: echo METANORMA_CLI_VERSION=${METANORMA_CLI_TAG#*/v} >> ${GITHUB_ENV}
      env:
        METANORMA_CLI_TAG: ${{ github.event.client_payload.ref }}

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true

    - name: Update Formula
      run: bundle exec generate-formula.rb --version ${METANORMA_CLI_VERSION}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push commit and tag
      run: |
        git config --global user.name "metanorma-ci"
        git config --global user.email "metanorma-ci@users.noreply.github.com"
        git add Formula/metanorma.rb Formula/metanorma-dev.rb formula-metadata.json
        git commit -m "Bump version to ${METANORMA_CLI_VERSION}"
        git tag v${METANORMA_CLI_VERSION}
        git push origin HEAD:${GITHUB_REF} --tags
