name: release-tag

on:
  repository_dispatch:
    types: [ metanorma/packed-mn ]

jobs:
  push-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.event.client_payload.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
    - run: |
        git config --global user.name "metanorma-ci"
        git config --global user.email "metanorma-ci@users.noreply.github.com"
    - name: Parse metanorma-cli version
      env:
        METANORMA_CLI_TAG: ${{ github.event.client_payload.ref }}
      run: |
        echo METANORMA_CLI_VERSION=${METANORMA_CLI_TAG#*/v} >> ${GITHUB_ENV}
    - name: Update Formula
      run: |
        ./formula-set-version.sh ${METANORMA_CLI_VERSION}
    - name: Push commit and tag
      run: |
        git add Formula/metanorma.rb Formula/metanorma-dev.rb
        git commit -m "Bump version to ${METANORMA_CLI_VERSION}"
        git tag v${METANORMA_CLI_VERSION}
        git push origin HEAD:${GITHUB_REF} --tags
